import Provider from '@/components/Provider';
import { ReactNode } from 'react';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface PropsType {
    children: ReactNode;
}

const RootLayout = ({ children }: PropsType) => {
    return (
        <html lang="en">
            <body>
                <Provider>{children}</Provider>
            </body>
        </html>
    );
};

export default RootLayout;
