export const subjectListInitialData = [
    {
        id: 0,
        subjectName: '국어',
        achievementLevel21: 'A',
        achievementLevel22: 'A',
        achievementLevel31: 'A',
    },
    {
        id: 1,
        subjectName: '사회',
        achievementLevel21: 'A',
        achievementLevel22: 'A',
        achievementLevel31: 'A',
    },
    {
        id: 2,
        subjectName: '역사',
        achievementLevel21: 'A',
        achievementLevel22: 'A',
        achievementLevel31: 'A',
    },
    {
        id: 3,
        subjectName: '도덕',
        achievementLevel21: 'A',
        achievementLevel22: 'A',
        achievementLevel31: 'A',
    },
    {
        id: 4,
        subjectName: '수학',
        achievementLevel21: 'A',
        achievementLevel22: 'A',
        achievementLevel31: 'A',
    },
    {
        id: 5,
        subjectName: '과학',
        achievementLevel21: 'A',
        achievementLevel22: 'A',
        achievementLevel31: 'A',
    },
    {
        id: 6,
        subjectName: '기술가정',
        achievementLevel21: 'A',
        achievementLevel22: 'A',
        achievementLevel31: 'A',
    },
    {
        id: 7,
        subjectName: '영어',
        achievementLevel21: 'A',
        achievementLevel22: 'A',
        achievementLevel31: 'A',
    },
    {
        id: 8,
        subjectName: '체육',
        achievementLevel21: 'A',
        achievementLevel22: 'A',
        achievementLevel31: 'A',
    },
    {
        id: 9,
        subjectName: '음악',
        achievementLevel21: 'A',
        achievementLevel22: 'A',
        achievementLevel31: 'A',
    },
    {
        id: 10,
        subjectName: '미술',
        achievementLevel21: 'A',
        achievementLevel22: 'A',
        achievementLevel31: 'A',
    },
    {
        id: 11,
        subjectName: '정보',
        achievementLevel21: 'A',
        achievementLevel22: 'A',
        achievementLevel31: 'A',
    },
];
