export { default as Box } from '@maru/ui/src/Box/Box';
export { default as PrivacyResponsibilityTeacher } from './ ResponsibilityTeacher/PrivacyResponsibilityTeacher';
export { default as CameraLocation } from './CameraLocation/CameraLocation';
export { default as CameraResponsibilityTeacher } from './ ResponsibilityTeacher/CameraResponsibilityTeacher';
export { default as CameraTime } from './CameraTime/CameraTime';
export { default as MainInformationBox } from './InformationBox/MainInformationBox';
export { default as PseudonymInformationBox } from './InformationBox/Pseudonym InformationBox';
export { default as PrivacyInformationBox } from './InformationBox/PrivactInformationBox';
export { default as ManagerTable } from './ManagerTable/ManagerTable';
export { default as InformationLocation } from './InformationLocation/InformationLocation';
export { default as OpenRequestBox } from './InformationBox/OpenRequestBox';
export { default as DeviceType } from './DeviceType/DeviceType';
export { default as ProcessingRestrictionsBox } from './InformationBox/ProcessingRestrictionsBox';
export { default as FilmingDay } from './FilmingDay/FilmingDay';
