name: Run Lighthouse CI When Push
on: [push]
jobs:
    lhci:
        name: Lighthouse CI
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js 19.7.0
              uses: actions/setup-node@v1
              with:
                  node-version: 19.7.0

            - name: Install packages
              run: |
                  npm install -g pnpm
                  pnpm install

            - name: Build
              run: |
                  pnpm run build

            - name: Install Lighthouse CLI
              run: |
                  npm install -g @lhci/cli

            - name: Run Lighthouse CI
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
              run: |
                  lhci autorun || echo "Fail to Run Lighthouse CI!"
